development:
  licenciamento_endpoint: https://www.vpsa.com.br/licenciamento/service/serviceBase
  usuario_endpoint: https://www.vpsa.com.br/vpsa/service/serviceUsuario
  clientes_url: https://www.vpsa.com.br/vpsa/rest/{base}/clientes/
  entidades_url: https://www.vpsa.com.br/vpsa/rest/{base}/entidades/
  pedidos_url: https://www.vpsa.com.br/estoque/rest/{base}/{entidade}/pedidos/
  produtos_url: https://www.vpsa.com.br/estoque/rest/{base}/{entidade}/produtos/
test:
  licenciamento_endpoint: https://www.vpsa.com.br/licenciamento/service/serviceBase
  usuario_endpoint: https://www.vpsa.com.br/vpsa/service/serviceUsuario
  clientes_url: https://www.vpsa.com.br/vpsa/rest/{base}/clientes/
  entidades_url: https://www.vpsa.com.br/vpsa/rest/{base}/entidades/
  pedidos_url: https://www.vpsa.com.br/estoque/rest/{base}/{entidade}/pedidos/
  produtos_url: https://www.vpsa.com.br/estoque/rest/{base}/{entidade}/produtos/
production:
  licenciamento_endpoint: https://www.vpsa.com.br/licenciamento/service/serviceBase
  usuario_endpoint: https://www.vpsa.com.br/vpsa/service/serviceUsuario
  clientes_url: https://www.vpsa.com.br/vpsa/rest/{base}/clientes/
  entidades_url: https://www.vpsa.com.br/vpsa/rest/{base}/entidades/
  pedidos_url: https://www.vpsa.com.br/estoque/rest/{base}/{entidade}/pedidos/
  produtos_url: https://www.vpsa.com.br/estoque/rest/{base}/{entidade}/produtos/